### ISSUE TITLE
Implement touch support for `esp32s2` and `esp32s3`.

### ISSUE THREAD

**Issue by jounathaen** [esp-rs/esp-hal#1905]
As of https://github.com/esp-rs/esp-hal/pull/1873, esp-hal only has touch support for the `esp32`. However, the `esp32s2` and `esp32s3` do also have touch peripherals.

The `esp32s3`'s peripheral has a rather similar structure as the `esp32`'s one, but judging from the datasheet, the `esp32s2`'s looks a little more different.

To get a starting point, I made have a very rough, incomplete and not working first attempt for the `esp32s3`, but at least it includes the pin definitions: https://github.com/jounathaen/esp-hal/tree/touch-esp32s3 
(As I don't have any hardware, (and honestly, also no motivating use-case), I will not continue with the implementation myself.)

**Comment by playfulFence** [comment]
I'm taking `esp32s2`.

**Comment by nponsard** [comment]
Hello, I am trying to add touch support for the `esp32s3`.
It seems like the file `esp-hal/src/touch.rs` is attempting to read/write to registers named differently between the `esp32` and `esp32s3`.
Where does board specific code need to be moved ? Is it the `esp-hal/src/soc` folders ?

**Comment by bugadani** [comment]
> Where does board specific code need to be moved ? Is it the esp-hal/src/soc folders ?

That sounds like a good place for now, yes.

**Comment by nponsard** [comment]
From what I read in the esp-idf source code, esp32s2 and esp32s3 uses the same 'version 2' touch hardware (from the comment in [touch_version_types.h](https://github.com/espressif/esp-idf/blob/master/components/esp_driver_touch_sens/hw_ver2/include/driver/touch_version_types.h)).

On my side I tried to loosely adapt the existing code for the esp32 to use the registers for the esp32s3, but it currently doesn't work. 

I probably need to do some tests without using the traits and structs already there for the esp32, so I can understand how to properly initialize everything.

If you want to take a look at my code (that is not working) it is available here https://github.com/nponsard/esp-hal/tree/feat/esp32s3-touch.

**Comment by nponsard** [comment]
> I looked at the code but the init phase and how to sample the pins is very different from the esp32 v1. This code as you mention you be different. Did you already have a working example without trying to implement the traits? Let me know, will give a try too. Will look at the c++/idf implementatiiom to get inspired.

Hello, I uploaded my test code here [https://github.com/nponsard/esp32s3-touch-test-](https://github.com/nponsard/esp32s3-touch-test-), you have to use my branch for it to compile. 

The initialization follows all the steps of the idf code, but I havent managed to get a good read.

**Comment by foldingbeauty** [comment]
@nponsard did you update your code with the right test?. I have more time to spend after the summer break and I want to take another look at your code and see if we can get a good read. Let me know if you have an update or use the code as-is to make it work.

**Comment by nponsard** [comment]
> [@nponsard](https://github.com/nponsard) did you update your code with the right test?. I have more time to spend after the summer break and I want to take another look at your code and see if we can get a good read. Let me know if you have an update or use the code as-is to make it work.

I'm sorry I couldn't find the project I was referring to. My esp-hal fork seems to have all the initialization bits I remember writing so maybe everything is already there.

**Comment by foldingbeauty** [comment]
update. I took @nponsard code  and created a new fork to find out why there is no clean read. you can find my work (in progress) here https://github.com/hi-squeaky-things/esp-hal 

I will start with the one-shot mode and I already can see the FSM of the touch device is not trigger, will focus on this first, also the PAC has some interesting nummering of the pads, which I already fixed in my code. The PAC is fine but you need to call the right touch_conf register.

Keep you all updated. I also got myself an esp32s2 so I can test it on a single xtensa cpu too.

Keep you updated on the progress. I will also test it against my own reference hardware platform (which contains a touch matrix):

https://github.com/hi-squeaky-things/little-squeaky-machine-hardware

**Comment by foldingbeauty** [comment]
Update. I ported most of the low level touch functions (from esp-idf) for the S2 en S3 but I also got stuck with not getting a  stable read or the FSM of the touch device is not getting started. My work can be found here: https://github.com/hi-squeaky-things/esp-hal/tree/develop_touch_esp32s3. 

I also took the code separated from esp-hal to use it directly; so I can quickly iterate and debug on the device. I don’t have a oscilloscope to check of the Finite State Machine is charging the pins, but will get one soon (ask a friend of my) to see if it’s a timing or another issue. I keep digging, but not yet some “white smoke”.  The separation of the code is the same test program I wrote in C++ using IDF, maybe there is an issue with init of the FSM in RTC IO section, will see. The init of the pins looks fine too. 

Example of my code on the device (mod touch_common;  is the code I also wrote here (https://github.com/hi-squeaky-things/esp-hal/blob/develop_touch_esp32s3/esp-hal/src/touch/esp32s3/touch_common.rs). Code is still quick and a bit dirty, still need a lot of touch-ups.

```rust
#![no_std]
#![no_main]

use esp_backtrace as _;
use esp_hal::{
    clock::CpuClock,
    delay::Delay,
    handler, main,
    peripherals::{self, Peripherals},
};
use esp_println::{print, println};

mod touch_common;
use touch_common::*;

esp_bootloader_esp_idf::esp_app_desc!();

#[main]
fn main() -> ! {
    esp_println::logger::init_logger_from_env();
    let config = esp_hal::Config::default().with_cpu_clock(CpuClock::max());
    esp_println::println!("-:= > Set CPU Speed to {:?}", config.cpu_clock());
    let peripherals = esp_hal::init(config);
    let delay = Delay::new();
  
    println!("touch init hal");
    touch_pad_init();
    
    println!("touch pad config");
    touch_pad_config(1);
    touch_pad_config(2);

    touch_pad_set_fsm_mode(touch_lowlevel_new::TouchFSMMode::TOUCH_FSM_MODE_TIMER);
    touch_pad_fsm_start();

    loop {
        delay.delay_millis(100);
        let mut data = touch_pad_read_raw_data(1);
        print!("T1: [{}] ", data);
        data = touch_pad_read_raw_data(2);
        println!("T2: [{}]", data);
    }
}

```

Keep you posted on the progress. My reference platform and touch pads work fine in esp-idf, getting close!

**Comment by georgik** [comment]
@foldingbeauty Do you have any updates? 

I've tried to port the change to esp-hal-1.1.0: https://github.com/georgik/esp-hal/pull/1
I'm trying to get it working with ESP-Rainbow - https://github.com/atomic14/esp32-zxspectrum ;-)
Still not working, because of some GPIO conflict in Rust.

The important thing to note, is that touch driver in ESP-IDF changes significantly between versions 4.4 and 6.0.
It's still possible to use old driver in ESP-IDF 6, it requires just `CONFIG_TOUCH_SUPPRESS_DEPRECATE_WARN=y`.
The thing is that for som solutions this might be the only solution.

The problem is partially in timing and it manifests in the way that old driver is able to read several touch inputs, while new driver on same hw might be able to read one or two with low precision.
